FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
COPY server/package*.json ./server/

ENV HUSKY=0
RUN npm pkg delete scripts.prepare
RUN npm ci

COPY server/ ./server/

WORKDIR /app/server

EXPOSE 5000

CMD ["npm", "run", "dev"]